### ISSUE TITLE
Crash when search gif in a tweet

### ISSUE THREAD

**Issue by espiguilla** [klinker24/Talon-for-Twitter#21]
when u search a gif, he make a crash 

ATAL EXCEPTION: main
                                                                           Process: com.klinker.android.twitter, PID: 2360
                                                                           java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                               at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:310)
                                                                               at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:279)
                                                                               at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:253)
                                                                               at android.support.v7.app.AppCompatDialog.setContentView(AppCompatDialog.java:76)
                                                                               at android.support.v7.app.AlertController.installContent(AlertController.java:213)
                                                                               at android.support.v7.app.AlertDialog.onCreate(AlertDialog.java:240)
                                                                               at android.app.Dialog.dispatchOnCreate(Dialog.java:394)
                                                                               at android.app.Dialog.show(Dialog.java:295)
                                                                               at com.klinker.android.twitter.ui.GiphySearch$6.onResponse(GiphySearch.java:139)
                                                                               at com.klinker.android.twitter.utils.api_helper.GiphyHelper$SearchGiffy.onPostExecute(GiphyHelper.java:114)
                                                                               at com.klinker.android.twitter.utils.api_helper.GiphyHelper$SearchGiffy.onPostExecute(GiphyHelper.java:52)
                                                                               at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                               at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                               at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:148)

**Comment by espiguilla** [comment]
When show de message of 3 mg of gifs, new AlertDialog.Builder(GiphySearch.this) crash because
class AlertDialog extends AppCompatDialog

**Comment by klinker24** [comment]
Thanks. Will post a new build in a bit to the play store.
